### ISSUE TITLE
Tips panel text feedback

### ISSUE THREAD

**Issue by ixje** [neo-project/neo-visual-tracker#105]
Moving feedback from discord to here per request;

![](https://raw.githubusercontent.com/neo-project/neo-visual-tracker/master/images/feature-invoke.png)

> I have just one remark on the "call vs invoke" text. I've historically experienced that many devs do not understand that they're not talking to the global blockchain and that a call is not persisted. As such "broadcast" might not mean anything to them. There is not enough real estate to describe that in a tips section without it becoming in-depth documentation, but perhaps we can say 

> "Calling a contract will invoke the method locally using the Neo Express instance, but not broadcast a transaction to the network to be persisted" .
that should take away some ambiguity

**Comment by djnicholson** [comment]
Thanks for the feedback @ixje, I agree. Feel free to submit a PR to change this. The HTML is here: https://github.com/neo-project/neo-visual-tracker/blob/master/src/panels/invoke.html (If you're not comfortable making the PR, I'll make the change you suggest at a later date.)
