### ISSUE TITLE
 npm update check failed 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#12]
On my machine, when I do npm run watch, I get an  npm update check failed error. I tried following the instructions in [this SO answer](https://stackoverflow.com/a/47861024) but no luck. @djnicholson thinks it might be a race condition since multiple watch processes cal npm update in parallel.

As a workaround, I use npm run compile, which works fine

**Comment by djnicholson** [comment]
Might get fixed by https://github.com/neo-project/neo-visual-tracker/pull/26, please check.  If that PR does not fix it, it will at least make it easier to debug what is happening.

**Comment by djnicholson** [comment]
Fixed by https://github.com/neo-project/neo-visual-tracker/pull/26
