### ISSUE TITLE
How to pass a ByteArray into contract parameters when invoking a contract?

### ISSUE THREAD

**Issue by joeqian10** [neo-project/neo-visual-tracker#129]
![image](https://user-images.githubusercontent.com/33386299/76190030-0708ab80-6217-11ea-85d9-0318997efff0.png)
Assume that I have a NEP5 asset script hash: 0x89fda5f88703a89087bab6ab1859f10849b153ed, what should I put in the first text box? 
I have tried:
0x89fda5f88703a89087bab6ab1859f10849b153ed,
ed53b14908f15918abb6ba8790a80387f8a5fd89,
"0x89fda5f88703a89087bab6ab1859f10849b153ed",
"ed53b14908f15918abb6ba8790a80387f8a5fd89",
@AdQk428wVzpkHTxc4MP5UMdsgNdrm36dyV,
"@AdQk428wVzpkHTxc4MP5UMdsgNdrm36dyV",

but none of these is successfully converted to a normal 20-byte long ByteArray!!!

**Comment by djnicholson** [comment]
Fixed by #125
