### ISSUE TITLE
Generate neo contract invoke files for Neo-Express v2

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#133]
In NeoExpress v2 (unreleased), the `contract invoke` command takes a path to an invoke file instead of taking script hash + arguments on the command line. This allows for arbitrarily complex arguments + the ability to check these invoke files into source control.

It would be great if Visual DevTracker could generate these files. The developer could specify the arguments in DevTracker's invoke UI which would have a new command UI for exporting the invoke parameters to disk.

The neo invoke file is documented in [design note NDX-DN12](https://github.com/ngdseattle/design-notes/blob/master/NDX-DN12%20-%20Neo%20Express%20Invoke%20Files.md).

**Comment by djnicholson** [comment]
Resolved by https://github.com/neo-project/neo-visual-tracker/pull/134
