### ISSUE TITLE
display application log for transactions

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#14]
Neo-express supports the [getapplicationlog](https://docs.neo.org/docs/en-us/reference/rpc/latest-version/api/getapplicationlog.html) RPC endpoint. This information should be retrievable (perhaps on request rather than by default) in the transaction viewer

**Comment by djnicholson** [comment]
See https://github.com/neo-project/neo-visual-tracker/pull/15

I'm just showing the JSON in the UI for now, but could add prettier formatting if desired.

**Comment by djnicholson** [comment]
Closing this, as the raw data is displayed now.  Issue https://github.com/neo-project/neo-visual-tracker/issues/19 tracks making it look prettier.
