### ISSUE TITLE
Support adding neo endpoints in tracker tree view manually

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#35]
THis allows a user to select a specific mainnet/testnet endpoint as well as support non-express private nets in devtracker.

THinking we should remove the mainnet and testnet defaults in the explorer but provide "add random mainnet/testnet RPC node" menu option that queries the monitor and populates the explorer as the user requests

**Comment by djnicholson** [comment]
I see two options for how to store these custom endpoints:
1. JSON file in the workspace
2. Persisted state for the vscode plugin

With option (1) users would potentially have different endpoints visible depending on what workspace they have open in vscode. They can also share the endpoints with others on their team (e.g. commit the JSON to version control).

With option (2) users would always see the same endpoints no matter what they are doing in vscode.  However it would not be easy to migrate the set of endpoints between different machines/team members.  This option does not create any visible "clutter" on disk (i.e. JSON files).

**Comment by devhawk** [comment]
I like the first option
