### ISSUE TITLE
Different logo for neo express instances in blockchain explorer.

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#65]
I've reached out to Neo marketing for a logo. In the meantime, there are a bunch of SVGs from the neo.org website [available](https://github.com/neo-project/neo.org/blob/master/NeoWeb/wwwroot/images/). In particular I thought the icon from inside the silhouette head of [CoreDeveloper](https://github.com/neo-project/neo.org/blob/master/NeoWeb/wwwroot/images/dev/CoreDeveloper.svg), [ToolsDeveloper](https://github.com/neo-project/neo.org/blob/master/NeoWeb/wwwroot/images/dev/ToolsDeveloper.svg) or [dApp Developer](https://github.com/neo-project/neo.org/blob/master/NeoWeb/wwwroot/images/dev/dAppDeveloper.svg) would work

**Comment by djnicholson** [comment]
bd13ee18da10424b92a0f42729eccab847e22c04
