### ISSUE TITLE
Create Neo Express command shouldn't be in the navigation group

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#66]
VS Code TreeView Guide [describes two ways](https://code.visualstudio.com/api/extension-guides/tree-view#view-actions) to attach a command to the view title: `location: view/title, group:navigation` for primary actions and `location: view/title` for secondary actions. Create neo express instance should be attached as a secondary action, (i.e. without `group:navigation`)

**Comment by djnicholson** [comment]
45f1713eb6676b1d04b20b82fb494096f56cfca8
