### ISSUE TITLE
When navigating back to Blocks panel, ensure block being viewed is still visible

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#67]
When the user navigates from the Block Detail panel back to the Blocks panel, that the Block that was being viewed may have scrolled off the page. Navigating to the Blocks page from the Blocks Detail page should ensure the page contains the block the user was looking at. Additionally, the block the user was looking should be subtly highlighted in some way

**Comment by djnicholson** [comment]
1fc26ec98a579d04dd2acc770b5d62934d254183
(highlighting still TODO)

**Comment by djnicholson** [comment]
435ecb25b31ee13e3b11a76fa4acbea951278fa2
