### ISSUE TITLE
Add Default or Last Used RPC node when executing operations directly on blockchain 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#80]
currently, if you execute an operation like claim or transfer directly on a blockchain instance, it asks you which RPC node to use every time. There should be a mechanism for devtracker to remember previously used node instead of asking the user every time.

THis could be done via a "default node" mechanism or by remembering the most recently used RPC node

**Comment by djnicholson** [comment]
9c3d5f30e16aee0be143593946c2c24d8a33fb59

**Comment by djnicholson** [comment]
Above mentioned commit did not work for @devhawk (per comment in PR #87)

**Comment by djnicholson** [comment]
I think we might have just had different expectations here :)

My change made it remember the last URL you use, and default to that URL next time you see the QuickPick URL (so you can just quickly hit Enter and use the same server as last time).  I think maybe you were expecting it to only ever show the QuickPick the first time ever (if we go with that approach though, we need an intuitive way to have the last used URL be "forgotten").

Thoughts?

**Comment by devhawk** [comment]
Yes, I was thinking the we would only see the quick pick if there wasn't already a default node set. I'm good with this approach for 1.0 and see how things look as more folks get their hands on this.
