### ISSUE TITLE
mechanism to add additional RPC nodes to MainNet/TestNet blockchain

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#81]
None of the CoZ testnet servers appear to support the getunspents RPC method, but those are the only ones that get populated. We need a way for users to specify their own - potentially custom - RPC nodes for mainnet and testnet (and arbitrary NEO blockchains in the future).

RPC nodes added this way would need to have their genesis block hash validated against at least one other existing RPC node for the blockchain.

Custom RPC nodes could be stored in a variety of places:
* ExtensionContext.globalState
* ExtensionContext.workspaceState
* a JSON document with custom extension in the workspace

**Comment by djnicholson** [comment]
c0b9d8b562b712253200e5b8667e0766ee33fcb2
