### ISSUE TITLE
When creating a NEP-6 wallet, save it to the workspace root 

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#83]
currently, when creating a NEP-6 wallet, the file needs to be saved by the user. Instead, we should save the wallet to the workspace root with the name "<wallet-name>.neo-wallet.json". If there is already a file with that name in the workspace root, then fall back to existing behavior

We could also attach this command to the file explorer folder menu so the user can create wallets in a specific folder under the root

**Comment by djnicholson** [comment]
Done in https://github.com/neo-project/neo-visual-tracker/tree/nep6
