### ISSUE TITLE
UI for advanced neo-express startup control

### ISSUE THREAD

**Issue by devhawk** [neo-project/neo-visual-tracker#92]
starting up a neo-express node has two "advanced" functions which are not surfaced via visual devtracker

* Specifying "seconds-per-block"
* Specifying a checkpoint to run

**Comment by djnicholson** [comment]
I don't see a command line option to specify a checkpoint. Is that an upcoming neo-express feature? Or is the plan to restore a checkpoint then run neo-express immediately after?

There is also a reset option, do we want to expose that?
